// @vitest-environment jsdom
import { fireEvent, render, screen } from "@testing-library/svelte";
import { expect, it, vi } from "vitest";
import { Playground } from "./playground.svelte";
import DisplayListInspector from "./DisplayListInspector.svelte";
import StepDock from "./StepDock.svelte";
import PlayerBar from "./PlayerBar.svelte";
import { inspectionTrace } from "./test/inspection";

it("starts collapsed and has a toggle even for static toys", async () => {
  const pg = new Playground();
  render(PlayerBar, {pg});
  render(DisplayListInspector, {pg});
  render(StepDock, {pg});
  expect(screen.queryByRole("button", {name:"Next command"})).not.toBeInTheDocument();
  expect(screen.queryByRole("button", {name:"Play"})).not.toBeInTheDocument();
  const toggle = screen.getByRole("button", {name:"Display list"});
  await fireEvent.click(toggle);
  expect(pg.inspection.open).toBe(true);
  expect(toggle).toHaveAttribute("aria-pressed","true");
  expect(screen.getByRole("button", {name:"Close display list"})).toHaveAttribute("aria-expanded","true");
  await fireEvent.click(screen.getByRole("button", {name:"Close display list"}));
  expect(pg.inspection.trace).toBeNull();
  expect(toggle).toHaveAttribute("aria-pressed","false");
});

it("pages commands, selects with arrows, links repeated rows and expands raw continuations", async () => {
  const pg = new Playground();
  const trace = inspectionTrace(205);
  trace.rows[101].line = 20;
  trace.rows[101].pc = trace.rows[1].pc;
  trace.rows[8].words.push({...trace.rows[8].words[0],pc:"0x00000200"});
  pg.inspection.open = true;
  pg.inspection.capture(trace);
  render(DisplayListInspector, {pg});
  render(StepDock, {pg});
  expect(screen.getAllByRole("button", {name:/^Command /})).toHaveLength(100);
  await fireEvent.click(screen.getByRole("button", {name:"Next page"}));
  expect(screen.getByText("Page 2 / 3")).toBeInTheDocument();
  const row = screen.getByRole("button", {name:"Command 101, G_MTX, line 20"});
  await fireEvent.click(row);
  expect(row).toHaveAttribute("aria-pressed","true");
  expect(screen.getByText("State after command 101")).toBeInTheDocument();
  await fireEvent.keyDown(row, {key:"ArrowUp"});
  expect(pg.inspection.selectedSeq).toBe(100);
  await fireEvent.keyDown(screen.getByRole("button", {name:"Command 100, G_MTX, line 119"}), {key:"ArrowUp"});
  expect(pg.inspection.selectedSeq).toBe(99);
  expect(screen.getByText("Page 1 / 3")).toBeInTheDocument();
  pg.inspectSourceLine(20);
  await vi.waitFor(() => expect(screen.getByRole("button", {name:"Command 1, G_MTX, line 20"})).toHaveClass("source-match"));
  await fireEvent.click(screen.getByRole("button", {name:"Next page"}));
  expect(screen.getByRole("button", {name:"Command 101, G_MTX, line 20"})).toHaveClass("source-match");
  pg.selectCommand(8);
  await vi.waitFor(() => expect(screen.getByText("run 3, op none, material 1, render mode 0")).toBeInTheDocument());
  const words = screen.getByText("Words for 8 · 1 continuation(s)");
  await fireEvent.click(words);
  expect(words.closest("details")).toHaveAttribute("open");
  expect(screen.getByText(/0x00000200: 0x05000000/)).toBeInTheDocument();
});

it("shows partial traces, emissions and terminal diagnostics, and disables stale stepping", async () => {
  const pg = new Playground();
  const trace = inspectionTrace();
  trace.termination = "cap";
  trace.diags = [{line:27,kind:"src",severity:"warn",msg:"missing render mode",seq:null,pc:trace.rows[8].pc}];
  trace.rows[8].draws = [{kind:"texRect",target:{pairIndex:1,colorImage:{fmt:0,siz:2,width:64,addr:"0x00100000"},depthImage:null,isDepthClear:false},opIndex:0,rect:[0,0,256,256],tile:3,uls:0,ult:0,dsdx:1024,dtdy:1024,flip:false,copyMode:true,fbSource:"0x00200000"}];
  pg.inspection.open = true;
  pg.inspection.capture(trace);
  render(DisplayListInspector, {pg});
  render(StepDock, {pg});
  await fireEvent.click(screen.getByRole("button", {name:"Next draw"}));
  expect(screen.getByText(/partial: cap/)).toBeInTheDocument();
  expect(screen.getByText(/Terminal diagnostic: missing render mode/)).toBeInTheDocument();
  expect(screen.getByText(/Framebuffer source: 0x00200000/)).toBeInTheDocument();
  expect(screen.getByText(/Explicit tile 3/)).toBeInTheDocument();
  pg.inspection.invalidate();
  await vi.waitFor(() => expect(screen.getByRole("button", {name:"Next command"})).toBeDisabled());
  expect(screen.getByRole("button", {name:"Command 8, G_TRI1, line 27"})).toBeDisabled();
  pg.stepCommand(-1);
  expect(pg.inspection.selectedSeq).toBe(8);
});
